version: '3'

includes:

  git:
    taskfile: ./git/Taskfile-git.yml

  org-to-md:docker: 
    taskfile: ./org/Taskfile-docker.yml

  org-to-md: 
    taskfile: ./org/Taskfile-org-to-md.yml

  dsl: 
    taskfile: ./dsl/Taskfile-dsl.yml